### ISSUE TITLE
User test - J, 30th - 15:00

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid.github.io#109]
Test performed in Ghent in person.

Driver: Vincent
Scribe: Michiel

Background: this person (J) used Solid during the class Software Engineering Lab 1 or 2 (wasn't sure), but didn't remember too much.
Description of Solid in own words: really no idea.

Takeaways: 

* as a developer, when you click 'get started' from 'peas in a pod', you get to use-solid, and there's no way to get from there to the getting-started section for developers
* site should be more oriented to programmers
* bug in right-hand menu on 'common patterns' page, same menu item shown twice
* bug in right-hand menu on for-developers/pod-server page, that's the menu for app-dev page

**Comment by michielbdejong** [comment]
* menu on the right of https://solid.github.io/for-developers/apps/tools should have more sub-section items
* there is no obvious way to add yourself as a pod provider on 'get a pod'
* this doesn't look like an open source project. there are no obvious links to github repos where i can contribute. a github logo somewhere would go a long way.
* 'become an identity provider' has very little explanation
* in Vocabularies>Code>QuickStart, it would be nice to have a consistent 'Next Step' link at the bottom
