### ISSUE TITLE
Breadcrumbs on /use-solid/apps links to /use-solid/ (with trailing slash), which is broken

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid.github.io#171]

**Comment by NSeydoux** [comment]
BOOM, fixed (I happened to fix it earlier ^^)

**Comment by Vinnl** [comment]
Cool @NSeydoux, what was the fix?

**Comment by NSeydoux** [comment]
To apply the same fix as for the post layout (namely prevent adding a slash for the last breadcrumb item), but in the pages layout. Now that I say that, it might be best to move the snippet of code managing breadcrumbs one layer up, so that it is shared between all the layouts that need it.
