### ISSUE TITLE
Several factual inaccuracies in FAQs

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid.github.io#204]
Several answers in the FAQ are factually incorrect or inaccurate and should be updated as soon as possible.
I suggest temporarily removing incorrect answers, and replacing them when they have been rewritten.

Factually incorrect (and thus urgent) answers include:
- What is a WebID?
- To what extent are Pods conceived as distinct from the WebIDs?
- Are Solid users expected to setup their own servers and self-host?
- When I want to leave a Pod provider, can I take my data with me?
- When using Solid, how is data stored?
- I just signed up but have two profile locations, what is the difference between the two?
- How can I delete my WebID?
- Is data in my Pod safe? Is the Pod encrypted while it is stored on a provider’s system?
- How will Solid prevent 3rd parties from replicating data?
- Does a copy of my data controlled by others exist?
- Could the Solid technology be a tool to trace or control criminal actions?
- Could Solid become another tech giant monopoly?
- What if I don’t want to share my data at all?
- Who controls the data of a child using Solid?

Inaccurate (less urgent) answers include:
- What exactly is personal data?
- How does Solid relate to other Web standards?
- Arguably the Semantic Web or Linked Data never took off, so why is Solid working with it?
- Is data on my Pod stored on a centralised server of the provider?
- If all my data is in one place, does it not become a vulnerable target for hackers?
- Can I make sure that nobody has a copy of my data?

**Comment by Mitzi-Laszlo** [comment]
pick up the green pen?

**Comment by RubenVerborgh** [comment]
As I've explained before, I find this a very harmful attitude.

In open source software projects, we thank people who submit an issue. It means they have spent time to try out something, long enough to find something that does not work as expected. Furthermore, they took the time to report it in sufficient detail to make clear what the problem is. They care enough to let the project owner know about it. This is a very valuable form of feedback.

If the default reaction to such feedback is an imperative to fix it, then we will see a decline in volunteers giving such important feedback.

So I do not appreciate the suggestion above; what I've done _is_ the green pen.

As for this concrete issue: I estimate the time for this to be fixed to be around 2 person-days of work, given the amount of writing involved. I currently do not have this amount of additional time available for spending on the Solid project given all the time I already spend as a volunteer. However, I am willing to contribute answers to specific questions should others get stuck.

Given the inaccuracies on the page, I would strongly suggest that it is removed or at least truncated very soon, based on the feedback abovoe. We cannot afford to spread misinformation. It can go back up when it is fixed and reviewed by multiple people for accuracy.
