### ISSUE TITLE
Solid Library Overview

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid.github.io#32]
How to pick an RDF library

List Solid related libraries and if they are for building apps, Pods, and/or identity providers. Include content from https://github.com/solid/releases

to be published on https://github.com/solid/solid.github.io/blob/master/pages/implement/library-overview.md

see https://github.com/solid/process/issues/169

**Comment by jeff-zucker** [comment]
I would advocate for not including libraries for pod and identity providers in the same place as libraries for app developers.  They are different audiences using different software stacks not related to each other.  There are going to be many sub-categories of tools for app development and mixing in pod and identity tools will only confuse things.   Are there any existing pod or identity provider tools?
