### ISSUE TITLE
This Week in Solid 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid.github.io#38]
Include link to https://tinyletter.com/TheSolidProject to the current solidproject.org so that people can sign up to This Week in Solid

Include the blog design on old This Week in Solid content for reference without having to sign up.

**Comment by justinwb** [comment]
What's the expectation for how these should be connected?

**Comment by Vinnl** [comment]
I would expect TWiS to be published on the new website in the future?
