### ISSUE TITLE
Design pages

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid.github.io#50]
Get the content of into the design existing templates:
* [This Week in Solid](https://solid.github.io/about/this-week-in-solid) (could be at the bottom of the home page invitation to sign up and then use the blog page design for the weekly updates. Still need a page for the This Week in Solid overview) to blog
* update the implement page to design

Pages that need design include: 
* [Solid Team](https://solid.github.io/about/team)
* [Solid Events](https://solid.github.io/about/solid-events) (could recycle Solid events map Tony made earlier in the year) 
* [press](https://solid.github.io/about/press)

Other: 
* [Standardisation](https://solid.github.io/standardisation) 
* [Use](https://solid.github.io/use)
* [Implement](https://solid.github.io/implement) this would be the page you get to when you press the **Big Purple Button**
* [FAQ](https://solid.github.io/about/faqs) 
* Include social media links: GitHub, twitter
* [Solid Challenges](https://solid.github.io/about/challenges)
* [License](https://solid.github.io/about/license) and 
* [Solid Logo and Usage Guidelines](https://solid.github.io/about/logo-usage-guidelines) 
* include acknowledgement of contributions from companies/ organisations

**Comment by justinwb** [comment]
Which pages need to be designed?

**Comment by Vinnl** [comment]
@justinwb Here are some examples:

- https://solid.github.io/about/solid-team
- https://solid.github.io/build/apps/first-app
- https://solid.github.io/build/apps/first-app/1-authentication
- https://solid.github.io/build/apps/first-app/2-understanding-solid
