### ISSUE TITLE
Link building is inconsistent from local docker-compose to deployment

### ISSUE THREAD

**Issue by NSeydoux** [solid/solid.github.io#72]
Links from (for instance, there are other examples) `https://solid.github.io/Learn/writing-solid-applications` to `https://solid.github.io/Learn/writing-solid-applications/1-authentication#` is badly generated in the deployed version, while it is correct when locally testing using docker-compose. 

In the deployed version, the last part of the URI (here writing-solid-applications) is not appended when referencing to a child page, leading to the generation of a broken link `https://solid.github.io/Learn/writing-solid-applications/1-authentication`. What is the correct way of writing relative links ?

**Comment by Vinnl** [comment]
Yeah I ran into this too. GitHub Pages has its own routing methods it seems. There used to be a `jekyll/jekyll:pages` Docker image, but that doesn't seem to work anymore for me - but you might want to give that a try instead, maybe it works for you.
