### ISSUE TITLE
Developer Feedback

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/solid.github.io#96]
Here are some notes of a conversation with a developer who tried working on Solid. 

Solid doesn't feed ready for developers because: 
* the call to action has been to get a Pod however the user experience of the Pod is a red flag because the interface is unworkable. Managed to make a file and think I made it public but I’m not sure. 
* Did the lunch break tutorial and managed data from the app. Did React sdk project - worked right out of the box - NPM package works well! Did the new website tutorial which was very similar to the lunch break tutorial but more clearly written. The app examples are quite simple, some are more complicated but are not well documented. The whole experience felt like a warm bath. And then confusion…
* When I’d finished all that I wondered how to connect it to a more complicated example and my own use case. How would you build something other than the tutorial? Would be nice to see a schematic of how to build the Solid architecture in a new use case. What if I want to make something more elaborate?

**Comment by michielbdejong** [comment]
@Mitzi-Laszlo would love it if you could connect me with this app developer so I can try to brainstorm with them about that for their specific use case.
